apiVersion: v1
kind: Service
metadata:
  name: st2-service
  namespace: stackstorm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: st2web
